[alembic]
script_location = migrations
sqlalchemy.url = postgresql://postgres:postgres@db:5432/recruitment_db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
